### ISSUE TITLE
Can't create uswgi.ini.new: permission denied

### ISSUE THREAD

**Issue by ikidd** [searxng/searxng-docker#376]
If I don't comment out `cap drop: ALL` in the docker compose, I get permission errors and Searxng won't run.  I either get permission issues in the log trying to create the uwsgi.ini.new file or a temp file uwsgi.XXXXXX

I saw the reference to remove cap drop in the README, and if I do that, it creates everything as it should and runs.  But if I put cap drop back in after the first run, the above errors will occur.

Seemed to work fine until last night, when Watchtower pulled down [2025.5.20-a195f52](https://hub.docker.com/layers/searxng/searxng/2025.5.20-a195f52/images/sha256-22cc594fb474e71b3573150a9abda1dd2a83ae59232658fd291e0da3f21200a4) .  Updating to [2025.5.20-ca67f1d](https://hub.docker.com/layers/searxng/searxng/2025.5.20-ca67f1d/images/sha256-6fb3fa547100eee33ebbec4a3a0908aee032623a08fc69bcad483fb6787ae7ac) does not seem to fix issue.

Changing tag in docker-compose.yml to [2025.5.18-5dff826](https://hub.docker.com/layers/searxng/searxng/2025.5.18-5dff826/images/sha256-b4401f07b0d0e1e4681aa34390253525b54b1e35831fb8714b6a8875df228dab) fixes issue and allows running with cap drop in place.

**Comment by unixfox** [comment]
Was fixed by https://github.com/searxng/searxng-docker/pull/375. Do a docker compose pull

**Comment by baskinsy** [comment]
Also needs a git pull to get the new compose file. CAP_DROP and CAP_ADD have been removed.

**Comment by ikidd** [comment]
Haha, I see https://github.com/searxng/searxng-docker/issues/377 in the Open issues now, it must have been transferred from searxng/searxng a minute or two after I searched Issues for a fix.  I still have a browser tab open that doesn't show that one in the Open issues list.

All good, I eventually figured this out by removing the cap portions manually and then watched the logs to see the errors and fixed them with applying the .new files in ./searxng

**Comment by unixfox** [comment]
Would advise against doing manual changes and just do a git pull. Otherwise the next git pull you will have some conflicts with the manual changes.
